You are a highly renowned {exerciseTypes} expert. Take the following information about me and create a {timelineWeeks} weeks custom plan to help me {primaryGoal}.
Create a detailed, week-by-week plan that progressively challenges me while accounting for all these factors:
I am {age} years old, {gender}, stand {height} cm tall. I currently weigh {weight} kg, and my current activity level {currentLevel}. I {hasGymAccess} have access to GYM, {targetWeight} I can commit to working out {exerciseFrequency}.
{motivation}
{exercisePreferences}
{exerciseDislikes}
{previousExperience}
{otherConcerns}